/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajoencuesta;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class AdministrarEncuestadores extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarEncuestadores
     */
    public AdministrarEncuestadores() {
        initComponents();
        cargarDatosEnc();
        setTitle("Admistrador de encuestadores");
        setSize(900, 600);
        this.setLocationRelativeTo(rootPane);
        this.btnModificar.setVisible(false);
        this.lblAuxiliar.setVisible(false);
    }
    public void barrer(){
        this.txtNombre.setText("");
        this.txtRut.setText("");
        this.txtPass.setText("");
    }
    public void cargarDatosEnc(){
        
        //llenar la tabla con lo datos contenidos en la base de datos
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("rut");
        model.addColumn("nombre");
        model.addColumn("pass");
        model.addColumn("estado de conexion");
        
        
        this.tblDatos.setModel(model);
        DefaultComboBoxModel combo=new DefaultComboBoxModel();
            System.out.println("tabla cambiada");
        String datosEncuesta[]=new String[4];
       
        try {
            //obtener registros desde la base de datos
            Statement stt=con.createStatement();
            ResultSet resultado=stt.executeQuery("Select * from encuestador");
            while(resultado.next()){
                datosEncuesta[0]=resultado.getString(1);
                datosEncuesta[1]=resultado.getString(2);
                datosEncuesta[2]=resultado.getString(3);
                datosEncuesta[3]=resultado.getString(4);
                
               
              
               
               model.addRow(datosEncuesta);
  
                
            }
            
            this.tblDatos.setModel(model);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"error al cargar los registro "+ e);
                    
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuEmergenteTabla = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        pnlFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblAuxiliar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        Modificar.setText("Modificar");
        Modificar.setToolTipText("");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        menuEmergenteTabla.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        menuEmergenteTabla.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1123, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 663, -1, -1));

        pnlFormulario.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setText("rut");

        jLabel2.setText("nombre usuario");

        jLabel3.setText("clave portal");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("ACTUALIZAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlFormularioLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre)
                                .addComponent(txtPass)))
                        .addGroup(pnlFormularioLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel1)
                            .addGap(55, 55, 55)
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAuxiliar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administracion de encuestadores");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 84, 487, 50));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.setComponentPopupMenu(menuEmergenteTabla);
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 137));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 430, 170, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo pantalla.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String rut=this.txtRut.getText();
        String nombre=this.txtNombre.getText();
        String pass=this.txtPass.getText();
        try {
            PreparedStatement stt=con.prepareStatement("insert into encuestador(rute,nombre,pass,estado) values("+rut+",'"+nombre+"','"+pass+"','inactivo');");
          //  stt.setString(1, rut);
            //stt.setString(2, nombre);
            //stt.setString(3, estatura);
            //stt.setString(4, peso);
            int x=stt.executeUpdate();
            if(x>0){
                JOptionPane.showMessageDialog(rootPane,"agregado correctamente a la base de datos");
                barrer();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,"No se pudo registrar en la base de datos "+e);
        }
        cargarDatosEnc();
        this.pnlFormulario.setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
     int fila=this.tblDatos.getSelectedRow();
           String codigo=tblDatos.getValueAt(fila, 0).toString();
            try{
            PreparedStatement st=con.prepareStatement("DELETE FROM encuestador WHERE  rute='"+codigo+"'");
            st.executeUpdate();
            cargarDatosEnc();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"error al eliminar los registros "+e);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        this.pnlFormulario.setVisible(true);
        this.btnModificar.setVisible(true);
        int fila=this.tblDatos.getSelectedRow();
           String codigo=tblDatos.getValueAt(fila, 0).toString();
        try {
            //obtener registros desde la base de datos
            Statement stt=con.createStatement();
            ResultSet resultado=stt.executeQuery("Select rute,nombre,pass from encuestador where rute="+codigo+";");
            while(resultado.next()){
             String rut=resultado.getString(1);
             String nombre=resultado.getString(2);
             String pass=resultado.getString(3);
             this.txtRut.setText(rut);
             this.txtNombre.setText(nombre);
             this.txtPass.setText(pass);
             this.lblAuxiliar.setText(rut);
                System.out.println(rut+nombre+pass);
              
               
             
  
                
            }
            
           
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"error al cargar los registro "+ e);
                    
        }
        cargarDatosEnc();
    }//GEN-LAST:event_ModificarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
      String rut=this.lblAuxiliar.getText();
        String nombre=this.txtNombre.getText();
        String pass=this.txtPass.getText();
        try{
    
    PreparedStatement sttt=con.prepareStatement("UPDATE encuestador set pass='"+pass+"',nombre='"+nombre+"' where rute="+rut+";");          
     sttt.executeUpdate();
          JOptionPane.showMessageDialog(rootPane, "registro Actualizado con exito");
          barrer();
          cargarDatosEnc();

  }catch(SQLException e){
      JOptionPane.showMessageDialog(rootPane, "se perdio la coneccion con el usuario "+e);
      
  }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarEncuestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarEncuestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarEncuestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarEncuestadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarEncuestadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuxiliar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPopupMenu menuEmergenteTabla;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
Conectar cone=new Conectar();
Connection con=cone.conexion();
}
